#!/bin/bash

### Get the ASM instance for this node from the /etc/oratab file
### The asm entry is maintained by the grid agent
ORACLE_SID=`grep +ASM /etc/oratab | cut -d':' -f1`
ORAENV_ASK=NO

### trim the number from the ORACLE_SID to get the cluster name
ORA_DBNAME=`echo ${ORACLE_SID} |tr -d [:digit:]`
export ORA_DBNAME

### call oraenv to set the environment
. /usr/local/bin/oraenv -s

### Cleanup
unset ORAENV_ASK

